CREATE TABLE IF NOT EXISTS plantel_users (
  id VARCHAR(64) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  avatar TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_plantel_users_email ON plantel_users(email);

CREATE TABLE IF NOT EXISTS plantel_workspaces (
  user_id VARCHAR(64) PRIMARY KEY REFERENCES plantel_users(id) ON UPDATE CASCADE ON DELETE CASCADE,
  animais JSONB NOT NULL DEFAULT '[]',
  areas JSONB NOT NULL DEFAULT '["Todos"]',
  theme VARCHAR(32) DEFAULT 'light',
  version BIGINT DEFAULT 1,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
